### ISSUE TITLE
Add setting to ellipsis truncate course names

### ISSUE THREAD

**Issue by azito122** [CLAMP-IT/moodle-blocks_filtered_course_list#104]
Course names can be pretty long. I think an option to automatically truncate course fullnames to a certain number of characters would be helpful.

e.g. "A Course Whose Name Is Simply Excessive In Its Length" becomes "A Course Whose..."

If @kwiliarty approves I've got some code and can do this without too much fuss (I think).

**Comment by kwiliarty** [comment]
Actually, you could truncate smartly even with a separate setting. So leave that concern out of the reckoning.

**Comment by azito122** [comment]
I like the idea of including it in the course name template. However, I'm not sure about truncating smartly -- do you mean truncating automatically based on the visual width of the block? Cause that'll get complicated.

**Comment by kwiliarty** [comment]
Sorry, that was vague. If you have a course name template setting like this: "FULLNAME (CATEGORY)" rendering like this:

> A very long coursename, which is not so unusual after all (Fall 2018)

A smart truncation would not lop off the category, but would look like this:

> A very long coursename... (Fall 2018)

**Comment by azito122** [comment]
Aha! Yes, adding length settings to the existing template field is a neat way around that problem. I'll submit a PR soon.
