### ISSUE TITLE
Data privacy null provider not found

### ISSUE THREAD

**Issue by kwiliarty** [CLAMP-IT/moodle-blocks_filtered_course_list#108]
On Moodle 3.5 (at least), the following error is appearing at `admin/tool/dataprivacy/pluginregistry.php`

>Fatal error: Interface 'core_privacy\metadata\null_provider' not found in /Users/kwiliarty/Sites/moodles/mgmaster/blocks/filtered_course_list/classes/privacy/provider.php on line 36

**Comment by azito122** [comment]
I believe it should be `\core_privacy\local\metadata\null_provider`?

**Comment by kwiliarty** [comment]
Yes. I am changing it and adding a test for it.

**Comment by kwiliarty** [comment]
Trying to add the test in the same step is confounding a simple fix. I'm just going to fix the bug for now and I'll create a separate issue for the test that we can pursue later.
