### ISSUE TITLE
suggestion: idnumber fillter

### ISSUE THREAD

**Issue by rimacher** [CLAMP-IT/moodle-blocks_filtered_course_list#142]
Hi,

Is it possible to use the regex fillter for the course idnumber rather than the shortname?

**Comment by kwiliarty** [comment]
It is not currently possible to filter by idnumber. I can add it as a desired enhancement.

**Comment by kwiliarty** [comment]
For Moodle 3.6 and 3.7 you can use version v4.2.0 of the block to have an idnumber filter. I'm in the process of backporting a version for Moodle 3.5 as well.
