### ISSUE TITLE
Configuring block breaks multilang title

### ISSUE THREAD

**Issue by rimacher** [CLAMP-IT/moodle-blocks_filtered_course_list#143]
Hello,

It appears there is bug in multilang systems.

Steps to replicate:

1. In a multilang system use language customisation and rename the block to correspond each language.
2. Add a new block to home page. Make sure block name is correct when alternating languages.
3. Change system language to English.
4. Turn editing on, configure the weight of the block and save.
5. Change to a different language.
6. Block name appears in English on all languages.

Thank you for the dedicated work on this amazing plugin.

**Comment by kwiliarty** [comment]
Thanks for pointing this out. I've looked into the issue and this is my current understanding of it: When you customize the block (by changing the weight or anything else) the plugin is saving the title as instance configuration on the block. I think that what I need to do is have the instance title be empty by default. This is how the HTML block works, for instance. Then I can display the language string for the block title if the instance setting is empty.

My only concern is that it will no longer be possible to set an empty title for an instance, but I think we can lose that behavior.
