### ISSUE TITLE
Does it work on Moodle 3.5 ?

### ISSUE THREAD

**Issue by T4m** [CLAMP-IT/moodle-blocks_filtered_course_list#144]
Thank you for this plugin. It is exactly what I need.

Unfortunately I can't make it work on Moodle 3.5. The plugin installation succeed, but the configuration of the plugin seems not saved or not used at all.

The block looks always the same, regardless how it is configured. I tried to configure globally (/admin/settings.php?section=blocksettingfiltered_course_list) and also through specific block configuration (also containing a field "Filter configuration"). In any case, when using the block, it looks always the same (displaying top level categories, and nothing else).

Also, I tried to clear the cache.

Using:
* Moodle 3.5.8
* blocks_filtered_course_list 3.6.1 (branch MOODLE_35)

Thank you for your help
Matthieu

**Comment by kwiliarty** [comment]
Hi Matthieu,

I'm assuming you are a site administrator. Have you changed the "Manager view" setting to "A manager sees own courses"? From what you are describing it sounds as if you may not have done that yet. It's easy to overlook.

Kevin

**Comment by T4m** [comment]
Thank you for the quick answer. I tried this checkbox. Unfortunately, it doesn't change anything. I also tried with a non-admin / non-manager account. The result is always a list of top level categories.

**Comment by kwiliarty** [comment]
Are you enrolled in any courses? What about the non-admin user you tried? Sorry if those seem like silly questions, but we have to rule out the easy solutions first. If either of those accounts is enrolled in courses, could you let me know which version of the plugin you are using and paste in the filter configuration you have set up? Or at least one version of it that you have tried? The plugin should certainly be working for Moodle 3.5, so I'll be happy to help you get to the bottom of this.

**Comment by T4m** [comment]
I finally understood. Thank you for the "not so silly" questions.

I didn't get that the base list for any filtering is already filtered by "current user is enroled in". That was not obvious to me. Also the fallback on first level categories (whenever you have no course to display?) didn't help me to understand what was happening.

I might need another plugin to be able to list course even where I'm not enrolled.

**Comment by kwiliarty** [comment]
I'm glad we figured it out, though it sounds like the plugin will not do what you are looking for. The Filtered Course List is principally a way to show users their own enrollments. The only exception to this is that you *can* filter on courses by enrollment method. If all and only the courses you need to display have, say, self-enrollment, then you could use that as a filtering principle. If you are a developer, it is also possible to write your own filter that would not need to be limited to the courses a user is enrolled in.
