### ISSUE TITLE
Moodle App support

### ISSUE THREAD

**Issue by Kemmotar83** [CLAMP-IT/moodle-blocks_filtered_course_list#147]
Hi,

We are using your plugin for years by now, but now we need to have it also on the mobile app. Are you planning to add mobile app support?

We can help you develop this feature and we already have analyzed your code. It's not really complex but sure a refactoring of block_filtered_course_list class it's needed (maybe only extracting service code in a dedicated class). This can't be done as a "simple and external pull request" but obviously you need to evaluate any pros and cons.

We already have done simple tests and if needed we discuss about it.

Thanks,
Giorgio

**Comment by kwiliarty** [comment]
Hi Giorgio,

I don't currently have any plans to provide mobile support, but I am not necessarily opposed to it, and I am open to collaboration. I know very little about the app, though, so please tell me more about what it would involve. My understanding is that the app does not render blocks. Is that correct? If so, what is the alternative in the context of the app?

**Comment by Kemmotar83** [comment]
Hi Kevin,

from version 3.8 Moodle supports Blocks in Moodle App (https://docs.moodle.org/38/en/Moodle_App_Block_support).

As you can see, there are 3 types of "rendering":
- title: not best solution in our case
- pre-rendered: it works with only 1 file addition (mobile.php) but it doesn't work very well
- full-support: this is obviously the best solution. It uses specific mobile templates but it requires more development work.

In my first comment I was talking about the third type. Since you already use templatable objects, we can reuse them and work in the renderer, switching between web and mobile rendering as needed.
The only problem here is that part of service code is inside block_filtered_course_list class, which cannot be called and instantiated from other classes (ie. mobile.php). We can extract everything not required by the block_base class and put it in a dedicated class, in order to use it both from mobile.php and block_filtered_course_list.php.

I've forked your repository. If it's ok for you, we'll work on that and we'll keep you updated.

Let me know.

Thanks,
Giorgio

**Comment by kwiliarty** [comment]
Thanks for the explanation; it's very helpful. Of course you should feel free to work on a fork. I'll look forward to seeing how things progress.

**Comment by Kemmotar83** [comment]
Hi Kevin,

here I am again. These months have been really busy but now we can continue the discussion on this subject.
We have already implemented the mobile support in our fork and we are ready for a pull request.

We have extracted the content class (block_content) from block_filtered_course_list.php and we have extracted the output objects from rendered.php. Finally we have created the template files for mobile rendering.

How do you intend to proceed? Obviously you'll want to analyze the code.

Giorgio

**Comment by kwiliarty** [comment]
Hi Giorgio,

Why don't you make the pull request so I can start looking at what it entails. I haven't developed anything for the mobile app yet, so I'll probably have a lot of questions, and some of them may be naive. One question that springs to mind: Were you able to write tests for the mobile environment? But I suppose I'll see that when I look at what you've written...

Cheers,
Kevin

**Comment by Kemmotar83** [comment]
Hi Kevin,

we are blocked with the development because we cannot understand how to get the block instance id inside the delegated method for the mobile visualization.
Everything works fine when there are only "global configured" instances on dashboard but, without instance id, we cannot manage local customizations.

There's no specific documentation on that, so I wrote in the Moodle Development forum hoping someone can help us.

I'll let you know when we'll have updates.

Giorgio

p.s. If you want to see the code written so far I can add you as contributor of the forked repository

**Comment by kwiliarty** [comment]
Ugh. Sorry to hear about the troubles. Thanks for all the effort you're putting into it. I'd be happy to see the code, though as I've admitted before, I haven't really worked with Moodle Mobile.

**Comment by Kemmotar83** [comment]
Hi Kevin,

to add mobile support we needed to refactor part of the code.
"...We have extracted the content class (block_content) from block_filtered_course_list.php and we have extracted the output objects from rendered.php...."

You can start analyzing that, ignoring the specific mobile code (few files).

Giorgio

**Comment by Kemmotar83** [comment]
Hi Kevin,

something is moving. Discussing with Dani Palou in the Moodle Forum it emerged that our problems were related to a Moodle App bug (https://tracker.moodle.org/browse/MOBILE-3596) and will be resolved with the next App release.

I'll let you know when we'll be ready with a new potential _pull request_.

Giorgio

**Comment by kwiliarty** [comment]
Oh, wow, it's great that you were able to get to the bottom of it. :-)

**Comment by Kemmotar83** [comment]
Hi Kevin,

good news. Moodle has released the updated Moodle App with the code fixed. Now the block it seems to work.

Now we'll try to rewrite the code in order to minimize the code changes from your original code.

Giorgio

**Comment by kwiliarty** [comment]
Scaling this issue back. Rather than providing full mobile support directly within this codebase, we will add a hook of sorts that will allow other parties to keep a clean mobile fork.
