### ISSUE TITLE
Help in implenting the block

### ISSUE THREAD

**Issue by alegiovanazzi** [CLAMP-IT/moodle-blocks_filtered_course_list#158]
Hi,

I'm new to Github and I pretty much don't know about code.

I describe my situation:
- Moodle 3.8
- Huge amount of (1) categories  (2)subcategories and (3)courses
- Need to create a block within the dashboard with all the sitewide completed (3)courses subdivided by (1)category
- Need to create in each (2)subcategory a block with the list of the (3)courses which aren't completed and the courses which are completed.

Is this feasible with this plugin?  
Is it possible to have support to do this (upon payment for sure)?

**Comment by kwiliarty** [comment]
Hi @alegiovanazzi ,

Thanks for your interest in the Filtered Course List. Unfortunately this plugin would be only an imperfect fit for your needs, I think.

On the dashboard you could include a block that shows a user their completed courses. You could not quite divide them by category, but you could include the immediate parent category (probably a subcategory) as part of the way each course is listed. 

You cannot get this:

### First Category
* Course 1
* Course 2
### Second Category
* Course 13

But you can get this:

### Completed Courses
* Course 1 (First Subcategory)
* Course 2 (Second Subcategory)
* Course 13 (Nth Subcategory)

In your subcategories you cannot get a block that shows completed or incomplete courses only in the subcategory. The closest I can think of would be a block that shows all the courses in the subcategory as well as a list of all completed and/or incomplete courses.

It's not a great fit, but maybe it would meet your need? I'm happy to try to help with configuration, but as I say, I don't think it's quite what you're looking for. Let me know. We don't offer any paid support, but I will help you if I can.

**Comment by alegiovanazzi** [comment]
Dear Kevin,

Having at least the list of completed courses would definitely be a big step forward.
And I thank you for the rapid answer.

I was able to create the block in the dashboard and at least show the list of completed courses.
completion | collapsed | Completed complete

I'm not managing to put the name of the subcategory the courses are linked to as the last entry.

Alessandro

**Comment by kwiliarty** [comment]
To add the immediate category to the course name you can modify the "Course name template" in the settings. If you set that field to `FULLNAME (CATEGORY)` then the block will display the course fullname followed by the name of the category in parentheses. The uppercase words `FULLNAME` and `CATEGORY` are special tokens that will be replaced the the relevant values from the course in question. Everything else will display as you enter it into the field, so you could also do something like `FULLNAME :: CATEGORY`, for instance.

**Comment by alegiovanazzi** [comment]
I'll try!

Alessandro
