### ISSUE TITLE
Master is no longer MOODLE 35 or Totara compat.

### ISSUE THREAD

**Issue by LiamKearn** [CLAMP-IT/moodle-blocks_filtered_course_list#179]
Just a heads up for anyone even though readme says 35 is supported by master you'll need to switch the to 35 branch

coursecat was recently changed to core_course_category but the README had not been updated!

Hope this helps

**Comment by mackensen** [comment]
@LiamKearn where are you looking? The current README.md for the most recent release says "For Moodle 3.8, 3.9, 3.10, and 3.11" (which is also outdated; Moodles 4.0 and 4.1 are supported).

**Comment by LiamKearn** [comment]
You are absolutely correct, no idea how I got there, probably recent lack of sleep.

Thanks for the response!
