### ISSUE TITLE
Add a language string for the "myaddinstance" capability

### ISSUE THREAD

**Issue by kwiliarty** [CLAMP-IT/moodle-blocks_filtered_course_list#2]
We need a language string to describe the capability to add a filtered course list block to a "My home" page.

**Comment by mackensen** [comment]
I'd have sworn we did that. Note that if you format the commit message as "Fix #2" it'll auto-close this issue.

**Comment by kwiliarty** [comment]
The ticket has been around for a while, and I think I closed it prematurely back on redmine. I didn't want to close the issue before a review. That was one of the questions I had about process.
