### ISSUE TITLE
Even better usage info

### ISSUE THREAD

**Issue by mudrd8mz** [CLAMP-IT/moodle-blocks_filtered_course_list#33]
I'm just thinking that the block has big potential that may not be that obvious / apparent from the current description and readme. Maybe a bit more illustrative screenshots or examples of actual naming patterns could give the visitors of https://moodle.org/plugins/block_filtered_course_list a better understanding what it is good for.

**Comment by kwiliarty** [comment]
I've created a wiki with fuller usage information and I'll start linking to it from the help strings for the plugin. This will also help me to simplify those strings to resolve #95.
