### ISSUE TITLE
Sort Order

### ISSUE THREAD

**Issue by tluger** [CLAMP-IT/moodle-blocks_filtered_course_list#44]
It appears the courses in a category sort by full name ascending by default. Is there a way to control the sort order? The default "My Courses" block allows for the sort order to be controlled by settings in the "Manage courses and categories" admin settings. My categories are set to sort by ID number. Those settings do not seem to affect this block.

**Comment by kwiliarty** [comment]
Thanks for your interest. If I understand what you are looking for, it should be quite doable, but just to confirm that I do understand you correctly: You'd like the sort order in the block to honor the sort order visible in and manageable from _Site administration > Courses > Manage courses and categories_. If that's what you have in mind, I would be happy to work on it. It seems to make a lot of sense. I'll want to think about whether it requires any additional settings and tests. In the meantime, it sounded in your other comment that you were open to hacking. I'm thinking it calls for something like this:
```
diff --git a/block_filtered_course_list.php b/block_filtered_course_list.php
index a76fc56..4cb9092 100644
--- a/block_filtered_course_list.php
+++ b/block_filtered_course_list.php
@@ -116,7 +116,7 @@ class block_filtered_course_list extends block_base {
         $this->content->footer = '';
         $this->context = context_system::instance();
 
-        $this->mycourses = enrol_get_my_courses(null, 'visible DESC, fullname ASC');
+        $this->mycourses = enrol_get_my_courses(null, 'visible DESC, sortorder ASC');
 
         // Obtain values from our config settings.
 
```

**Comment by tluger** [comment]
Thanks for the reply and the code. We will give it a try. You are correct in your interpretation of what I am asking about. The settings page for the regular my courses block allows for honoring the sort order in this way. It's pretty handy. 

We categorize groups of courses on our site in a number of different ways. One is by event. We have an annual conference, for which we webcast many of the presentations. We find it most convenient for our customers to be able to see the list of presentations they have signed up for in chronological order by date and time. I control this by using an ascending alphanumeric code in the ID number field for each course and set the category to sort by the ID number. 

Another scenario is courses that are grouped because they are part of a series. The courses are meant to be completed in a certain order. So I again use ID numbers to ensure that the courses will sort in that order rather than alphabetically. .

**Comment by tluger** [comment]
Hi

I can report the hack worked. The courses now sort by the sort order set in the course and category manager. 

Thank you so much for this great block and the custom code!

Todd

**Comment by kwiliarty** [comment]
Glad to hear it. I'll soon have a commit that allows you to select sorting principles from the admin GUI so you won't be left dragging your patch along.
