### ISSUE TITLE
Renderers or templates

### ISSUE THREAD

**Issue by Kemmotar83** [CLAMP-IT/moodle-blocks_filtered_course_list#49]
Hi,
to really improve this great plugin it could be very useful if you could use renderers or templates instead of hardcoded code.

Thank you very much,
Giorgio

**Comment by kwiliarty** [comment]
Thank you for the suggestion. I will look into it after settling some of the other outstanding issues.

**Comment by kwiliarty** [comment]
I'm going to split the transition up into smaller discrete commits. I'll keep this open until they are done. First up, a footer template: #59 .
