### ISSUE TITLE
Custom label order

### ISSUE THREAD

**Issue by Kemmotar83** [CLAMP-IT/moodle-blocks_filtered_course_list#50]
Hi,

it would be great to have the possibility to order the custom label already defined.

Example:
I have 5 custom labels and I want to introduce a sixth label as the top one.
Now I have increase labelscount, move (cut and paste) all the current labels down by one position and then write the new one on first position (custom label 1).

Thank you very much,
Giorgio

**Comment by kwiliarty** [comment]
Thanks @Kemmotar83 . I agree. I think this is a good next thing to tackle.

**Comment by mackensen** [comment]
A couple of us discussed this in CLAMP Slack with @kwiliarty and we came up with a broader proposal. We think the custom label structure should be dropped altogether in favor of a textarea with pipe-limited entries, one per line. You could have something like this:

```
Spring 2016 Courses|Spring 2016|1
Spring 2015 Courses|Spring 2016|0
```

This would correspond to the existing description, shortname selector, and whether to expand. You could have an unlimited number of labels, and re-sorting would be trivial.

**Comment by kwiliarty** [comment]
I like this approach a lot @mackensen . Many thanks. So what do you think about also replacing the built-in "Current" and "Future" labels as well?

**Comment by mackensen** [comment]
@kwiliarty I think it makes sense to fold them into the single textarea.

**Comment by kwiliarty** [comment]
Thanks @mackensen, I've been thinking about this a lot over the past week, and I feel the same way. I'm even wondering if we should not include the category config in the textarea. Right now the block has some limitations that have more to do with the configuration interface than with coding or display -- for instance, the idea that the block uses either shortnames or category structure but not both. We would need an additional field in each line to identify the filter type, but then the code could be built around the idea of parsing a line and passing back an array of rubrics where each rubric has a title, a list of course ids, and a default expansion state. I feel the code would be more modular this way, and also more extensible. We could add further types as desired. "Recent courses" comes to mind as something that has been suggested in the past.

**Comment by Kemmotar83** [comment]
Thanks @kwiliarty and @mackensen, I really like the "textarea" approach, it's far more flexible than now.
What @kwiliarty suggests in the last reply is really interesting because it allow the addition of more filtering criteria (shortname, category, starting time, ecc.) and maybe in the future this "filters" could be managed as sub-plugins.

**Comment by kwiliarty** [comment]
I agree, @Kemmotar83 . I've started working on it, and I think it's going to bring a number of changes for the better. Thanks again for the nudge.
