### ISSUE TITLE
Avoid xdebug timeout issue on 3.2

### ISSUE THREAD

**Issue by mackensen** [CLAMP-IT/moodle-blocks_filtered_course_list#51]
The moodle-plugin-ci docs recommend eliminating xdebug in the before_install stage before composer self-updates and the plugin is installed. I had incorporated this step into report_roster, but at the before_script stage. This did not actually disable xdebug, as you can see from the following test results:

* [Moodle 3.1](https://travis-ci.org/mackensen/moodle-report_roster/jobs/174339185)
* [Moodle 3.2 beta](https://travis-ci.org/mackensen/moodle-report_roster/jobs/174339189)

Apparently there's enough overhead on Moodle 3.2 with xdebug enabled that the CSS parser hits the 30 second timeout, causing the tests to fail. Compare the following test result on Moodle 3.2 with xdebug removal in the before_install stage:

* https://travis-ci.org/mackensen/moodle-report_roster/jobs/174360239

Xdebug is actually disabled, and the test passes.

**Comment by kwiliarty** [comment]
Many thanks for the heads-up!
