### ISSUE TITLE
Can't access permissions editing for block instance

### ISSUE THREAD

**Issue by erezerezg** [CLAMP-IT/moodle-blocks_filtered_course_list#74]
Hello,
Great plugin, thank you. I'm having trouble accessing the above in order to grant access only to certain roles. When I try to access the generic 'permissions' edit page like on any other block, I get redirected here: _OUR_MOODLE_INSTANCE_/admin/roles/permissions.php?contextid=1&returnurl=%2Fadmin%2Fsettings.php%3Fsection%3Dblocksettingfiltered_course_list

with the following error message:
_Cannot override base role capabilities_
_**Debug info:** 
Error code: cannotoverridebaserole
×**Stack trace:**
line 496 of /lib/setuplib.php: moodle_exception thrown
line 102 of /admin/roles/permissions.php: call to print_error()_

Thanks in advance,
Erez

**Comment by kwiliarty** [comment]
Thanks for reporting that, @erezerezg . I can recreate the problem and will try to fix it soon. It may take a couple weeks because of other things currently in my schedule.
