### ISSUE TITLE
Add course summary url for template

### ISSUE THREAD

**Issue by Kemmotar83** [CLAMP-IT/moodle-blocks_filtered_course_list#83]
It could be useful to add the _course summary url_ (http://.../course/info.php?id=####) in data exported for _list_item_ template.
It's a simple code modification but maybe useful for people like us that rely on summary pages in order to display information about courses.

Giorgio

**Comment by kwiliarty** [comment]
Hi @Kemmotar83 . I'm open to that suggestion, but I am curious:

I think of the course summary pages as being most useful to people who are not (yet) enrolled in a course whereas the Filtered Course List generally displays only the courses a user is already enrolled in. (The exceptions to this are anonymous visitors and admins, the latter depending on config settings.) Are you using the course summary pages as a resource for enrolled users? 

Thanks for your input.

Kevin

**Comment by kwiliarty** [comment]
@Kemmotar83 Is this the kind of adjustment you're looking for?

https://github.com/kwiliarty/moodle-blocks_filtered_course_list/commit/6b81adf50e148d5951b8c5a7fb7f4209591895bc

(Ignore the change in the .travis.yml file; it has nothing to do with this issue, but Travis tests were failing incorrectly without it.)

**Comment by Kemmotar83** [comment]
Hi @kwiliarty , sorry for the late reply.

I know that the summary is most useful for not enrolled users but there are some cases in which it could be useful to give a quick access to summary also for already enrolled users.
For example, in our university, we use the summary to display course programs and if you give a quick access to that page you don't have to replicate the same information inside the course.

Anyway, I checked your commit and it's exactly what I need.

Thank you,
Giorgio

**Comment by kwiliarty** [comment]
Thanks for the input, @Kemmotar83 . I'll integrate that feature and do a dot release.
