### ISSUE TITLE
Use translatable strings for settings dropdowns

### ISSUE THREAD

**Issue by dinism** [CLAMP-IT/moodle-blocks_filtered_course_list#97]
# TIA
![imagem](https://user-images.githubusercontent.com/14828021/35356444-514a9b5e-0148-11e8-9529-2ad918312e78.png)

**Comment by kwiliarty** [comment]
Yes, those are just the display texts. The values are not available for translation.

**Comment by kwiliarty** [comment]
It would probably be good to use whatever expression Moodle core uses for other `shortname` fields for the "Short name" string. I probably should have built it that way myself, but you don't need to wait for me to do that. I'll make an issue for it here, but it might be some time before it gets into a release.

**Comment by kwiliarty** [comment]
I've just created #98.

**Comment by kwiliarty** [comment]
Well, I have to correct myself now. Those strings are not currently translatable. Sorry. That increases the urgency of the patch, I'm sure. Let me see what I can do.

**Comment by dinism** [comment]
TIA

**Comment by kwiliarty** [comment]
@dinism I'm hopeful that I've now addressed all the string issues. All of the strings in this current round of updates were already available from core. Thank you for your patience and for your contribution to making the Filtered Course List a better plugin.

**Comment by dinism** [comment]
YOU ARE WELCOME. THANKS A LOT
